/*
  Simple DirectMedia Layer
  Copyright (C) 1997-2018 Sam Lantinga <slouken@libsdl.org>

  This software is provided 'as-is', without any express or implied
  warranty.  In no event will the authors be held liable for any damages
  arising from the use of this software.

  Permission is granted to anyone to use this software for any purpose,
  including commercial applications, and to alter it and redistribute it
  freely, subject to the following restrictions:

  1. The origin of this software must not be misrepresented; you must not
     claim that you wrote the original software. If you use this software
     in a product, an acknowledgment in the product documentation would be
     appreciated but is not required.
  2. Altered source versions must be plainly marked as such, and must not be
     misrepresented as being the original software.
  3. This notice may not be removed or altered from any source distribution.
*/

#include "SDL_ps5osmesa.h"

#if SDL_VIDEO_OPENGL_OSMESA

#ifndef GL_GLEXT_PROTOTYPES
#define GL_GLEXT_PROTOTYPES 1
#endif

#ifndef USE_MGL_NAMESPACE
#define USE_MGL_NAMESPACE 1
#endif

#include <GL/osmesa.h>
#include <dlfcn.h>

static struct {
    const char *name;
    void* addr;
} osmesa_symtab[] = {
    {"glAccum", (void*)glAccum},
    {"glActiveTexture", (void*)glActiveTexture},
    {"glActiveTextureARB", (void*)glActiveTextureARB},
    {"glAlphaFragmentOp1ATI", (void*)glAlphaFragmentOp1ATI},
    {"glAlphaFragmentOp2ATI", (void*)glAlphaFragmentOp2ATI},
    {"glAlphaFragmentOp3ATI", (void*)glAlphaFragmentOp3ATI},
    {"glAlphaFunc", (void*)glAlphaFunc},
    {"glAreProgramsResidentNV", (void*)glAreProgramsResidentNV},
    {"glAreTexturesResident", (void*)glAreTexturesResident},
    {"glAreTexturesResidentEXT", (void*)glAreTexturesResidentEXT},
    {"glArrayElement", (void*)glArrayElement},
    {"glArrayElementEXT", (void*)glArrayElementEXT},
    {"glAttachObjectARB", (void*)glAttachObjectARB},
    {"glAttachShader", (void*)glAttachShader},
    {"glBegin", (void*)glBegin},
    {"glBeginFragmentShaderATI", (void*)glBeginFragmentShaderATI},
    {"glBeginQuery", (void*)glBeginQuery},
    {"glBeginQueryARB", (void*)glBeginQueryARB},
    {"glBindAttribLocation", (void*)glBindAttribLocation},
    {"glBindAttribLocationARB", (void*)glBindAttribLocationARB},
    {"glBindBuffer", (void*)glBindBuffer},
    {"glBindBufferARB", (void*)glBindBufferARB},
    {"glBindFragmentShaderATI", (void*)glBindFragmentShaderATI},
    {"glBindFramebufferEXT", (void*)glBindFramebufferEXT},
    {"glBindProgramARB", (void*)glBindProgramARB},
    {"glBindProgramNV", (void*)glBindProgramNV},
    {"glBindRenderbufferEXT", (void*)glBindRenderbufferEXT},
    {"glBindTexture", (void*)glBindTexture},
    {"glBindTextureEXT", (void*)glBindTextureEXT},
    {"glBitmap", (void*)glBitmap},
    {"glBlendColor", (void*)glBlendColor},
    {"glBlendColorEXT", (void*)glBlendColorEXT},
    {"glBlendEquation", (void*)glBlendEquation},
    {"glBlendEquationEXT", (void*)glBlendEquationEXT},
    {"glBlendEquationSeparate", (void*)glBlendEquationSeparate},
    {"glBlendFunc", (void*)glBlendFunc},
    {"glBlendFuncSeparate", (void*)glBlendFuncSeparate},
    {"glBlendFuncSeparateEXT", (void*)glBlendFuncSeparateEXT},
    {"glBufferData", (void*)glBufferData},
    {"glBufferDataARB", (void*)glBufferDataARB},
    {"glBufferSubData", (void*)glBufferSubData},
    {"glBufferSubDataARB", (void*)glBufferSubDataARB},
    {"glCallList", (void*)glCallList},
    {"glCallLists", (void*)glCallLists},
    {"glCheckFramebufferStatusEXT", (void*)glCheckFramebufferStatusEXT},
    {"glClear", (void*)glClear},
    {"glClearAccum", (void*)glClearAccum},
    {"glClearColor", (void*)glClearColor},
    {"glClearDepth", (void*)glClearDepth},
    {"glClearIndex", (void*)glClearIndex},
    {"glClearStencil", (void*)glClearStencil},
    {"glClientActiveTexture", (void*)glClientActiveTexture},
    {"glClientActiveTextureARB", (void*)glClientActiveTextureARB},
    {"glClipPlane", (void*)glClipPlane},
    {"glColor3b", (void*)glColor3b},
    {"glColor3bv", (void*)glColor3bv},
    {"glColor3d", (void*)glColor3d},
    {"glColor3dv", (void*)glColor3dv},
    {"glColor3f", (void*)glColor3f},
    {"glColor3fv", (void*)glColor3fv},
    {"glColor3i", (void*)glColor3i},
    {"glColor3iv", (void*)glColor3iv},
    {"glColor3s", (void*)glColor3s},
    {"glColor3sv", (void*)glColor3sv},
    {"glColor3ub", (void*)glColor3ub},
    {"glColor3ubv", (void*)glColor3ubv},
    {"glColor3ui", (void*)glColor3ui},
    {"glColor3uiv", (void*)glColor3uiv},
    {"glColor3us", (void*)glColor3us},
    {"glColor3usv", (void*)glColor3usv},
    {"glColor4b", (void*)glColor4b},
    {"glColor4bv", (void*)glColor4bv},
    {"glColor4d", (void*)glColor4d},
    {"glColor4dv", (void*)glColor4dv},
    {"glColor4f", (void*)glColor4f},
    {"glColor4fv", (void*)glColor4fv},
    {"glColor4i", (void*)glColor4i},
    {"glColor4iv", (void*)glColor4iv},
    {"glColor4s", (void*)glColor4s},
    {"glColor4sv", (void*)glColor4sv},
    {"glColor4ub", (void*)glColor4ub},
    {"glColor4ubv", (void*)glColor4ubv},
    {"glColor4ui", (void*)glColor4ui},
    {"glColor4uiv", (void*)glColor4uiv},
    {"glColor4us", (void*)glColor4us},
    {"glColor4usv", (void*)glColor4usv},
    {"glColorFragmentOp1ATI", (void*)glColorFragmentOp1ATI},
    {"glColorFragmentOp2ATI", (void*)glColorFragmentOp2ATI},
    {"glColorFragmentOp3ATI", (void*)glColorFragmentOp3ATI},
    {"glColorMask", (void*)glColorMask},
    {"glColorMaterial", (void*)glColorMaterial},
    {"glColorPointer", (void*)glColorPointer},
    {"glColorPointerEXT", (void*)glColorPointerEXT},
    {"glColorSubTable", (void*)glColorSubTable},
    {"glColorTable", (void*)glColorTable},
    {"glColorTableEXT", (void*)glColorTableEXT},
    {"glColorTableParameterfv", (void*)glColorTableParameterfv},
    {"glColorTableParameteriv", (void*)glColorTableParameteriv},
    {"glCombinerInputNV", (void*)glCombinerInputNV},
    {"glCombinerOutputNV", (void*)glCombinerOutputNV},
    {"glCombinerParameterfNV", (void*)glCombinerParameterfNV},
    {"glCombinerParameterfvNV", (void*)glCombinerParameterfvNV},
    {"glCombinerParameteriNV", (void*)glCombinerParameteriNV},
    {"glCombinerParameterivNV", (void*)glCombinerParameterivNV},
    {"glCompileShader", (void*)glCompileShader},
    {"glCompileShaderARB", (void*)glCompileShaderARB},
    {"glCompressedTexImage1D", (void*)glCompressedTexImage1D},
    {"glCompressedTexImage1DARB", (void*)glCompressedTexImage1DARB},
    {"glCompressedTexImage2D", (void*)glCompressedTexImage2D},
    {"glCompressedTexImage2DARB", (void*)glCompressedTexImage2DARB},
    {"glCompressedTexImage3D", (void*)glCompressedTexImage3D},
    {"glCompressedTexImage3DARB", (void*)glCompressedTexImage3DARB},
    {"glCompressedTexSubImage1D", (void*)glCompressedTexSubImage1D},
    {"glCompressedTexSubImage1DARB", (void*)glCompressedTexSubImage1DARB},
    {"glCompressedTexSubImage2D", (void*)glCompressedTexSubImage2D},
    {"glCompressedTexSubImage2DARB", (void*)glCompressedTexSubImage2DARB},
    {"glCompressedTexSubImage3D", (void*)glCompressedTexSubImage3D},
    {"glCompressedTexSubImage3DARB", (void*)glCompressedTexSubImage3DARB},
    {"glConvolutionFilter1D", (void*)glConvolutionFilter1D},
    {"glConvolutionFilter2D", (void*)glConvolutionFilter2D},
    {"glConvolutionParameterf", (void*)glConvolutionParameterf},
    {"glConvolutionParameterfv", (void*)glConvolutionParameterfv},
    {"glConvolutionParameteri", (void*)glConvolutionParameteri},
    {"glConvolutionParameteriv", (void*)glConvolutionParameteriv},
    {"glCopyColorSubTable", (void*)glCopyColorSubTable},
    {"glCopyColorTable", (void*)glCopyColorTable},
    {"glCopyConvolutionFilter1D", (void*)glCopyConvolutionFilter1D},
    {"glCopyConvolutionFilter2D", (void*)glCopyConvolutionFilter2D},
    {"glCopyPixels", (void*)glCopyPixels},
    {"glCopyTexImage1D", (void*)glCopyTexImage1D},
    {"glCopyTexImage1DEXT", (void*)glCopyTexImage1DEXT},
    {"glCopyTexImage2D", (void*)glCopyTexImage2D},
    {"glCopyTexImage2DEXT", (void*)glCopyTexImage2DEXT},
    {"glCopyTexSubImage1D", (void*)glCopyTexSubImage1D},
    {"glCopyTexSubImage1DEXT", (void*)glCopyTexSubImage1DEXT},
    {"glCopyTexSubImage2D", (void*)glCopyTexSubImage2D},
    {"glCopyTexSubImage2DEXT", (void*)glCopyTexSubImage2DEXT},
    {"glCopyTexSubImage3D", (void*)glCopyTexSubImage3D},
    {"glCopyTexSubImage3DEXT", (void*)glCopyTexSubImage3DEXT},
    {"glCreateProgram", (void*)glCreateProgram},
    {"glCreateProgramObjectARB", (void*)glCreateProgramObjectARB},
    {"glCreateShader", (void*)glCreateShader},
    {"glCreateShaderObjectARB", (void*)glCreateShaderObjectARB},
    {"glCullFace", (void*)glCullFace},
    {"glDeleteBuffers", (void*)glDeleteBuffers},
    {"glDeleteBuffersARB", (void*)glDeleteBuffersARB},
    {"glDeleteFragmentShaderATI", (void*)glDeleteFragmentShaderATI},
    {"glDeleteFramebuffersEXT", (void*)glDeleteFramebuffersEXT},
    {"glDeleteLists", (void*)glDeleteLists},
    {"glDeleteObjectARB", (void*)glDeleteObjectARB},
    {"glDeleteProgram", (void*)glDeleteProgram},
    {"glDeleteProgramsARB", (void*)glDeleteProgramsARB},
    {"glDeleteProgramsNV", (void*)glDeleteProgramsNV},
    {"glDeleteQueries", (void*)glDeleteQueries},
    {"glDeleteQueriesARB", (void*)glDeleteQueriesARB},
    {"glDeleteRenderbuffersEXT", (void*)glDeleteRenderbuffersEXT},
    {"glDeleteShader", (void*)glDeleteShader},
    {"glDeleteTextures", (void*)glDeleteTextures},
    {"glDeleteTexturesEXT", (void*)glDeleteTexturesEXT},
    {"glDepthFunc", (void*)glDepthFunc},
    {"glDepthMask", (void*)glDepthMask},
    {"glDepthRange", (void*)glDepthRange},
    {"glDetachObjectARB", (void*)glDetachObjectARB},
    {"glDetachShader", (void*)glDetachShader},
    {"glDisable", (void*)glDisable},
    {"glDisableClientState", (void*)glDisableClientState},
    {"glDisableVertexAttribArray", (void*)glDisableVertexAttribArray},
    {"glDisableVertexAttribArrayARB", (void*)glDisableVertexAttribArrayARB},
    {"glDrawArrays", (void*)glDrawArrays},
    {"glDrawArraysEXT", (void*)glDrawArraysEXT},
    {"glDrawBuffer", (void*)glDrawBuffer},
    {"glDrawBuffers", (void*)glDrawBuffers},
    {"glDrawBuffersARB", (void*)glDrawBuffersARB},
    {"glDrawBuffersATI", (void*)glDrawBuffersATI},
    {"glDrawElements", (void*)glDrawElements},
    {"glDrawPixels", (void*)glDrawPixels},
    {"glDrawRangeElements", (void*)glDrawRangeElements},
    {"glDrawRangeElementsEXT", (void*)glDrawRangeElementsEXT},
    {"glEdgeFlag", (void*)glEdgeFlag},
    {"glEdgeFlagPointer", (void*)glEdgeFlagPointer},
    {"glEdgeFlagPointerEXT", (void*)glEdgeFlagPointerEXT},
    {"glEdgeFlagv", (void*)glEdgeFlagv},
    {"glEnable", (void*)glEnable},
    {"glEnableClientState", (void*)glEnableClientState},
    {"glEnableVertexAttribArray", (void*)glEnableVertexAttribArray},
    {"glEnableVertexAttribArrayARB", (void*)glEnableVertexAttribArrayARB},
    {"glEnd", (void*)glEnd},
    {"glEndFragmentShaderATI", (void*)glEndFragmentShaderATI},
    {"glEndList", (void*)glEndList},
    {"glEndQuery", (void*)glEndQuery},
    {"glEndQueryARB", (void*)glEndQueryARB},
    {"glEvalCoord1d", (void*)glEvalCoord1d},
    {"glEvalCoord1dv", (void*)glEvalCoord1dv},
    {"glEvalCoord1f", (void*)glEvalCoord1f},
    {"glEvalCoord1fv", (void*)glEvalCoord1fv},
    {"glEvalCoord2d", (void*)glEvalCoord2d},
    {"glEvalCoord2dv", (void*)glEvalCoord2dv},
    {"glEvalCoord2f", (void*)glEvalCoord2f},
    {"glEvalCoord2fv", (void*)glEvalCoord2fv},
    {"glEvalMesh1", (void*)glEvalMesh1},
    {"glEvalMesh2", (void*)glEvalMesh2},
    {"glEvalPoint1", (void*)glEvalPoint1},
    {"glEvalPoint2", (void*)glEvalPoint2},
    {"glExecuteProgramNV", (void*)glExecuteProgramNV},
    {"glFeedbackBuffer", (void*)glFeedbackBuffer},
    {"glFinalCombinerInputNV", (void*)glFinalCombinerInputNV},
    {"glFinish", (void*)glFinish},
    {"glFlush", (void*)glFlush},
    {"glFlushVertexArrayRangeNV", (void*)glFlushVertexArrayRangeNV},
    {"glFogCoordPointer", (void*)glFogCoordPointer},
    {"glFogCoordPointerEXT", (void*)glFogCoordPointerEXT},
    {"glFogCoordd", (void*)glFogCoordd},
    {"glFogCoorddEXT", (void*)glFogCoorddEXT},
    {"glFogCoorddv", (void*)glFogCoorddv},
    {"glFogCoorddvEXT", (void*)glFogCoorddvEXT},
    {"glFogCoordf", (void*)glFogCoordf},
    {"glFogCoordfEXT", (void*)glFogCoordfEXT},
    {"glFogCoordfv", (void*)glFogCoordfv},
    {"glFogCoordfvEXT", (void*)glFogCoordfvEXT},
    {"glFogf", (void*)glFogf},
    {"glFogfv", (void*)glFogfv},
    {"glFogi", (void*)glFogi},
    {"glFogiv", (void*)glFogiv},
    {"glFramebufferRenderbufferEXT", (void*)glFramebufferRenderbufferEXT},
    {"glFramebufferTexture1DEXT", (void*)glFramebufferTexture1DEXT},
    {"glFramebufferTexture2DEXT", (void*)glFramebufferTexture2DEXT},
    {"glFramebufferTexture3DEXT", (void*)glFramebufferTexture3DEXT},
    {"glFrontFace", (void*)glFrontFace},
    {"glFrustum", (void*)glFrustum},
    {"glGenBuffers", (void*)glGenBuffers},
    {"glGenBuffersARB", (void*)glGenBuffersARB},
    {"glGenFragmentShadersATI", (void*)glGenFragmentShadersATI},
    {"glGenFramebuffersEXT", (void*)glGenFramebuffersEXT},
    {"glGenLists", (void*)glGenLists},
    {"glGenProgramsARB", (void*)glGenProgramsARB},
    {"glGenProgramsNV", (void*)glGenProgramsNV},
    {"glGenQueries", (void*)glGenQueries},
    {"glGenQueriesARB", (void*)glGenQueriesARB},
    {"glGenRenderbuffersEXT", (void*)glGenRenderbuffersEXT},
    {"glGenTextures", (void*)glGenTextures},
    {"glGenTexturesEXT", (void*)glGenTexturesEXT},
    {"glGenerateMipmapEXT", (void*)glGenerateMipmapEXT},
    {"glGetActiveAttrib", (void*)glGetActiveAttrib},
    {"glGetActiveAttribARB", (void*)glGetActiveAttribARB},
    {"glGetActiveUniform", (void*)glGetActiveUniform},
    {"glGetActiveUniformARB", (void*)glGetActiveUniformARB},
    {"glGetAttachedObjectsARB", (void*)glGetAttachedObjectsARB},
    {"glGetAttachedShaders", (void*)glGetAttachedShaders},
    {"glGetAttribLocation", (void*)glGetAttribLocation},
    {"glGetAttribLocationARB", (void*)glGetAttribLocationARB},
    {"glGetBooleanv", (void*)glGetBooleanv},
    {"glGetBufferParameteriv", (void*)glGetBufferParameteriv},
    {"glGetBufferParameterivARB", (void*)glGetBufferParameterivARB},
    {"glGetBufferPointerv", (void*)glGetBufferPointerv},
    {"glGetBufferPointervARB", (void*)glGetBufferPointervARB},
    {"glGetBufferSubData", (void*)glGetBufferSubData},
    {"glGetBufferSubDataARB", (void*)glGetBufferSubDataARB},
    {"glGetClipPlane", (void*)glGetClipPlane},
    {"glGetColorTable", (void*)glGetColorTable},
    {"glGetColorTableEXT", (void*)glGetColorTableEXT},
    {"glGetColorTableParameterfv", (void*)glGetColorTableParameterfv},
    {"glGetColorTableParameterfvEXT", (void*)glGetColorTableParameterfvEXT},
    {"glGetColorTableParameteriv", (void*)glGetColorTableParameteriv},
    {"glGetColorTableParameterivEXT", (void*)glGetColorTableParameterivEXT},
    {"glGetCombinerInputParameterfvNV", (void*)glGetCombinerInputParameterfvNV},
    {"glGetCombinerInputParameterivNV", (void*)glGetCombinerInputParameterivNV},
    {"glGetCombinerOutputParameterfvNV", (void*)glGetCombinerOutputParameterfvNV},
    {"glGetCombinerOutputParameterivNV", (void*)glGetCombinerOutputParameterivNV},
    {"glGetCompressedTexImage", (void*)glGetCompressedTexImage},
    {"glGetCompressedTexImageARB", (void*)glGetCompressedTexImageARB},
    {"glGetConvolutionFilter", (void*)glGetConvolutionFilter},
    {"glGetConvolutionParameterfv", (void*)glGetConvolutionParameterfv},
    {"glGetConvolutionParameteriv", (void*)glGetConvolutionParameteriv},
    {"glGetDoublev", (void*)glGetDoublev},
    {"glGetError", (void*)glGetError},
    {"glGetFinalCombinerInputParameterfvNV", (void*)glGetFinalCombinerInputParameterfvNV},
    {"glGetFinalCombinerInputParameterivNV", (void*)glGetFinalCombinerInputParameterivNV},
    {"glGetFloatv", (void*)glGetFloatv},
    {"glGetFramebufferAttachmentParameterivEXT", (void*)glGetFramebufferAttachmentParameterivEXT},
    {"glGetHandleARB", (void*)glGetHandleARB},
    {"glGetHistogram", (void*)glGetHistogram},
    {"glGetHistogramParameterfv", (void*)glGetHistogramParameterfv},
    {"glGetHistogramParameteriv", (void*)glGetHistogramParameteriv},
    {"glGetInfoLogARB", (void*)glGetInfoLogARB},
    {"glGetIntegerv", (void*)glGetIntegerv},
    {"glGetLightfv", (void*)glGetLightfv},
    {"glGetLightiv", (void*)glGetLightiv},
    {"glGetMapdv", (void*)glGetMapdv},
    {"glGetMapfv", (void*)glGetMapfv},
    {"glGetMapiv", (void*)glGetMapiv},
    {"glGetMaterialfv", (void*)glGetMaterialfv},
    {"glGetMaterialiv", (void*)glGetMaterialiv},
    {"glGetMinmax", (void*)glGetMinmax},
    {"glGetMinmaxParameterfv", (void*)glGetMinmaxParameterfv},
    {"glGetMinmaxParameteriv", (void*)glGetMinmaxParameteriv},
    {"glGetObjectParameterfvARB", (void*)glGetObjectParameterfvARB},
    {"glGetObjectParameterivARB", (void*)glGetObjectParameterivARB},
    {"glGetPixelMapfv", (void*)glGetPixelMapfv},
    {"glGetPixelMapuiv", (void*)glGetPixelMapuiv},
    {"glGetPixelMapusv", (void*)glGetPixelMapusv},
    {"glGetPointerv", (void*)glGetPointerv},
    {"glGetPointervEXT", (void*)glGetPointervEXT},
    {"glGetPolygonStipple", (void*)glGetPolygonStipple},
    {"glGetProgramEnvParameterdvARB", (void*)glGetProgramEnvParameterdvARB},
    {"glGetProgramEnvParameterfvARB", (void*)glGetProgramEnvParameterfvARB},
    {"glGetProgramInfoLog", (void*)glGetProgramInfoLog},
    {"glGetProgramLocalParameterdvARB", (void*)glGetProgramLocalParameterdvARB},
    {"glGetProgramLocalParameterfvARB", (void*)glGetProgramLocalParameterfvARB},
    {"glGetProgramNamedParameterdvNV", (void*)glGetProgramNamedParameterdvNV},
    {"glGetProgramNamedParameterfvNV", (void*)glGetProgramNamedParameterfvNV},
    {"glGetProgramParameterdvNV", (void*)glGetProgramParameterdvNV},
    {"glGetProgramParameterfvNV", (void*)glGetProgramParameterfvNV},
    {"glGetProgramStringARB", (void*)glGetProgramStringARB},
    {"glGetProgramStringNV", (void*)glGetProgramStringNV},
    {"glGetProgramiv", (void*)glGetProgramiv},
    {"glGetProgramivARB", (void*)glGetProgramivARB},
    {"glGetProgramivNV", (void*)glGetProgramivNV},
    {"glGetQueryObjectiv", (void*)glGetQueryObjectiv},
    {"glGetQueryObjectivARB", (void*)glGetQueryObjectivARB},
    {"glGetQueryObjectuiv", (void*)glGetQueryObjectuiv},
    {"glGetQueryObjectuivARB", (void*)glGetQueryObjectuivARB},
    {"glGetQueryiv", (void*)glGetQueryiv},
    {"glGetQueryivARB", (void*)glGetQueryivARB},
    {"glGetRenderbufferParameterivEXT", (void*)glGetRenderbufferParameterivEXT},
    {"glGetSeparableFilter", (void*)glGetSeparableFilter},
    {"glGetShaderInfoLog", (void*)glGetShaderInfoLog},
    {"glGetShaderSource", (void*)glGetShaderSource},
    {"glGetShaderSourceARB", (void*)glGetShaderSourceARB},
    {"glGetShaderiv", (void*)glGetShaderiv},
    {"glGetString", (void*)glGetString},
    {"glGetTexEnvfv", (void*)glGetTexEnvfv},
    {"glGetTexEnviv", (void*)glGetTexEnviv},
    {"glGetTexGendv", (void*)glGetTexGendv},
    {"glGetTexGenfv", (void*)glGetTexGenfv},
    {"glGetTexGeniv", (void*)glGetTexGeniv},
    {"glGetTexImage", (void*)glGetTexImage},
    {"glGetTexLevelParameterfv", (void*)glGetTexLevelParameterfv},
    {"glGetTexLevelParameteriv", (void*)glGetTexLevelParameteriv},
    {"glGetTexParameterfv", (void*)glGetTexParameterfv},
    {"glGetTexParameteriv", (void*)glGetTexParameteriv},
    {"glGetTrackMatrixivNV", (void*)glGetTrackMatrixivNV},
    {"glGetUniformLocation", (void*)glGetUniformLocation},
    {"glGetUniformLocationARB", (void*)glGetUniformLocationARB},
    {"glGetUniformfv", (void*)glGetUniformfv},
    {"glGetUniformfvARB", (void*)glGetUniformfvARB},
    {"glGetUniformiv", (void*)glGetUniformiv},
    {"glGetUniformivARB", (void*)glGetUniformivARB},
    {"glGetVertexAttribPointerv", (void*)glGetVertexAttribPointerv},
    {"glGetVertexAttribPointervARB", (void*)glGetVertexAttribPointervARB},
    {"glGetVertexAttribPointervNV", (void*)glGetVertexAttribPointervNV},
    {"glGetVertexAttribdv", (void*)glGetVertexAttribdv},
    {"glGetVertexAttribdvARB", (void*)glGetVertexAttribdvARB},
    {"glGetVertexAttribdvNV", (void*)glGetVertexAttribdvNV},
    {"glGetVertexAttribfv", (void*)glGetVertexAttribfv},
    {"glGetVertexAttribfvARB", (void*)glGetVertexAttribfvARB},
    {"glGetVertexAttribfvNV", (void*)glGetVertexAttribfvNV},
    {"glGetVertexAttribiv", (void*)glGetVertexAttribiv},
    {"glGetVertexAttribivARB", (void*)glGetVertexAttribivARB},
    {"glGetVertexAttribivNV", (void*)glGetVertexAttribivNV},
    {"glHint", (void*)glHint},
    {"glHistogram", (void*)glHistogram},
    {"glIndexMask", (void*)glIndexMask},
    {"glIndexPointer", (void*)glIndexPointer},
    {"glIndexPointerEXT", (void*)glIndexPointerEXT},
    {"glIndexd", (void*)glIndexd},
    {"glIndexdv", (void*)glIndexdv},
    {"glIndexf", (void*)glIndexf},
    {"glIndexfv", (void*)glIndexfv},
    {"glIndexi", (void*)glIndexi},
    {"glIndexiv", (void*)glIndexiv},
    {"glIndexs", (void*)glIndexs},
    {"glIndexsv", (void*)glIndexsv},
    {"glIndexub", (void*)glIndexub},
    {"glIndexubv", (void*)glIndexubv},
    {"glInitNames", (void*)glInitNames},
    {"glInterleavedArrays", (void*)glInterleavedArrays},
    {"glIsBuffer", (void*)glIsBuffer},
    {"glIsBufferARB", (void*)glIsBufferARB},
    {"glIsEnabled", (void*)glIsEnabled},
    {"glIsFramebufferEXT", (void*)glIsFramebufferEXT},
    {"glIsList", (void*)glIsList},
    {"glIsProgram", (void*)glIsProgram},
    {"glIsProgramARB", (void*)glIsProgramARB},
    {"glIsProgramNV", (void*)glIsProgramNV},
    {"glIsQuery", (void*)glIsQuery},
    {"glIsQueryARB", (void*)glIsQueryARB},
    {"glIsRenderbufferEXT", (void*)glIsRenderbufferEXT},
    {"glIsShader", (void*)glIsShader},
    {"glIsTexture", (void*)glIsTexture},
    {"glIsTextureEXT", (void*)glIsTextureEXT},
    {"glLightModelf", (void*)glLightModelf},
    {"glLightModelfv", (void*)glLightModelfv},
    {"glLightModeli", (void*)glLightModeli},
    {"glLightModeliv", (void*)glLightModeliv},
    {"glLightf", (void*)glLightf},
    {"glLightfv", (void*)glLightfv},
    {"glLighti", (void*)glLighti},
    {"glLightiv", (void*)glLightiv},
    {"glLineStipple", (void*)glLineStipple},
    {"glLineWidth", (void*)glLineWidth},
    {"glLinkProgram", (void*)glLinkProgram},
    {"glLinkProgramARB", (void*)glLinkProgramARB},
    {"glListBase", (void*)glListBase},
    {"glLoadIdentity", (void*)glLoadIdentity},
    {"glLoadMatrixd", (void*)glLoadMatrixd},
    {"glLoadMatrixf", (void*)glLoadMatrixf},
    {"glLoadName", (void*)glLoadName},
    {"glLoadProgramNV", (void*)glLoadProgramNV},
    {"glLoadTransposeMatrixd", (void*)glLoadTransposeMatrixd},
    {"glLoadTransposeMatrixdARB", (void*)glLoadTransposeMatrixdARB},
    {"glLoadTransposeMatrixf", (void*)glLoadTransposeMatrixf},
    {"glLoadTransposeMatrixfARB", (void*)glLoadTransposeMatrixfARB},
    {"glLockArraysEXT", (void*)glLockArraysEXT},
    {"glLogicOp", (void*)glLogicOp},
    {"glMap1d", (void*)glMap1d},
    {"glMap1f", (void*)glMap1f},
    {"glMap2d", (void*)glMap2d},
    {"glMap2f", (void*)glMap2f},
    {"glMapBuffer", (void*)glMapBuffer},
    {"glMapBufferARB", (void*)glMapBufferARB},
    {"glMapGrid1d", (void*)glMapGrid1d},
    {"glMapGrid1f", (void*)glMapGrid1f},
    {"glMapGrid2d", (void*)glMapGrid2d},
    {"glMapGrid2f", (void*)glMapGrid2f},
    {"glMaterialf", (void*)glMaterialf},
    {"glMaterialfv", (void*)glMaterialfv},
    {"glMateriali", (void*)glMateriali},
    {"glMaterialiv", (void*)glMaterialiv},
    {"glMatrixMode", (void*)glMatrixMode},
    {"glMinmax", (void*)glMinmax},
    {"glMultMatrixd", (void*)glMultMatrixd},
    {"glMultMatrixf", (void*)glMultMatrixf},
    {"glMultTransposeMatrixd", (void*)glMultTransposeMatrixd},
    {"glMultTransposeMatrixdARB", (void*)glMultTransposeMatrixdARB},
    {"glMultTransposeMatrixf", (void*)glMultTransposeMatrixf},
    {"glMultTransposeMatrixfARB", (void*)glMultTransposeMatrixfARB},
    {"glMultiDrawArrays", (void*)glMultiDrawArrays},
    {"glMultiDrawArraysEXT", (void*)glMultiDrawArraysEXT},
    {"glMultiDrawElements", (void*)glMultiDrawElements},
    {"glMultiDrawElementsEXT", (void*)glMultiDrawElementsEXT},
    {"glMultiTexCoord1d", (void*)glMultiTexCoord1d},
    {"glMultiTexCoord1dARB", (void*)glMultiTexCoord1dARB},
    {"glMultiTexCoord1dv", (void*)glMultiTexCoord1dv},
    {"glMultiTexCoord1dvARB", (void*)glMultiTexCoord1dvARB},
    {"glMultiTexCoord1f", (void*)glMultiTexCoord1f},
    {"glMultiTexCoord1fARB", (void*)glMultiTexCoord1fARB},
    {"glMultiTexCoord1fv", (void*)glMultiTexCoord1fv},
    {"glMultiTexCoord1fvARB", (void*)glMultiTexCoord1fvARB},
    {"glMultiTexCoord1i", (void*)glMultiTexCoord1i},
    {"glMultiTexCoord1iARB", (void*)glMultiTexCoord1iARB},
    {"glMultiTexCoord1iv", (void*)glMultiTexCoord1iv},
    {"glMultiTexCoord1ivARB", (void*)glMultiTexCoord1ivARB},
    {"glMultiTexCoord1s", (void*)glMultiTexCoord1s},
    {"glMultiTexCoord1sARB", (void*)glMultiTexCoord1sARB},
    {"glMultiTexCoord1sv", (void*)glMultiTexCoord1sv},
    {"glMultiTexCoord1svARB", (void*)glMultiTexCoord1svARB},
    {"glMultiTexCoord2d", (void*)glMultiTexCoord2d},
    {"glMultiTexCoord2dARB", (void*)glMultiTexCoord2dARB},
    {"glMultiTexCoord2dv", (void*)glMultiTexCoord2dv},
    {"glMultiTexCoord2dvARB", (void*)glMultiTexCoord2dvARB},
    {"glMultiTexCoord2f", (void*)glMultiTexCoord2f},
    {"glMultiTexCoord2fARB", (void*)glMultiTexCoord2fARB},
    {"glMultiTexCoord2fv", (void*)glMultiTexCoord2fv},
    {"glMultiTexCoord2fvARB", (void*)glMultiTexCoord2fvARB},
    {"glMultiTexCoord2i", (void*)glMultiTexCoord2i},
    {"glMultiTexCoord2iARB", (void*)glMultiTexCoord2iARB},
    {"glMultiTexCoord2iv", (void*)glMultiTexCoord2iv},
    {"glMultiTexCoord2ivARB", (void*)glMultiTexCoord2ivARB},
    {"glMultiTexCoord2s", (void*)glMultiTexCoord2s},
    {"glMultiTexCoord2sARB", (void*)glMultiTexCoord2sARB},
    {"glMultiTexCoord2sv", (void*)glMultiTexCoord2sv},
    {"glMultiTexCoord2svARB", (void*)glMultiTexCoord2svARB},
    {"glMultiTexCoord3d", (void*)glMultiTexCoord3d},
    {"glMultiTexCoord3dARB", (void*)glMultiTexCoord3dARB},
    {"glMultiTexCoord3dv", (void*)glMultiTexCoord3dv},
    {"glMultiTexCoord3dvARB", (void*)glMultiTexCoord3dvARB},
    {"glMultiTexCoord3f", (void*)glMultiTexCoord3f},
    {"glMultiTexCoord3fARB", (void*)glMultiTexCoord3fARB},
    {"glMultiTexCoord3fv", (void*)glMultiTexCoord3fv},
    {"glMultiTexCoord3fvARB", (void*)glMultiTexCoord3fvARB},
    {"glMultiTexCoord3i", (void*)glMultiTexCoord3i},
    {"glMultiTexCoord3iARB", (void*)glMultiTexCoord3iARB},
    {"glMultiTexCoord3iv", (void*)glMultiTexCoord3iv},
    {"glMultiTexCoord3ivARB", (void*)glMultiTexCoord3ivARB},
    {"glMultiTexCoord3s", (void*)glMultiTexCoord3s},
    {"glMultiTexCoord3sARB", (void*)glMultiTexCoord3sARB},
    {"glMultiTexCoord3sv", (void*)glMultiTexCoord3sv},
    {"glMultiTexCoord3svARB", (void*)glMultiTexCoord3svARB},
    {"glMultiTexCoord4d", (void*)glMultiTexCoord4d},
    {"glMultiTexCoord4dARB", (void*)glMultiTexCoord4dARB},
    {"glMultiTexCoord4dv", (void*)glMultiTexCoord4dv},
    {"glMultiTexCoord4dvARB", (void*)glMultiTexCoord4dvARB},
    {"glMultiTexCoord4f", (void*)glMultiTexCoord4f},
    {"glMultiTexCoord4fARB", (void*)glMultiTexCoord4fARB},
    {"glMultiTexCoord4fv", (void*)glMultiTexCoord4fv},
    {"glMultiTexCoord4fvARB", (void*)glMultiTexCoord4fvARB},
    {"glMultiTexCoord4i", (void*)glMultiTexCoord4i},
    {"glMultiTexCoord4iARB", (void*)glMultiTexCoord4iARB},
    {"glMultiTexCoord4iv", (void*)glMultiTexCoord4iv},
    {"glMultiTexCoord4ivARB", (void*)glMultiTexCoord4ivARB},
    {"glMultiTexCoord4s", (void*)glMultiTexCoord4s},
    {"glMultiTexCoord4sARB", (void*)glMultiTexCoord4sARB},
    {"glMultiTexCoord4sv", (void*)glMultiTexCoord4sv},
    {"glMultiTexCoord4svARB", (void*)glMultiTexCoord4svARB},
    {"glNewList", (void*)glNewList},
    {"glNormal3b", (void*)glNormal3b},
    {"glNormal3bv", (void*)glNormal3bv},
    {"glNormal3d", (void*)glNormal3d},
    {"glNormal3dv", (void*)glNormal3dv},
    {"glNormal3f", (void*)glNormal3f},
    {"glNormal3fv", (void*)glNormal3fv},
    {"glNormal3i", (void*)glNormal3i},
    {"glNormal3iv", (void*)glNormal3iv},
    {"glNormal3s", (void*)glNormal3s},
    {"glNormal3sv", (void*)glNormal3sv},
    {"glNormalPointer", (void*)glNormalPointer},
    {"glNormalPointerEXT", (void*)glNormalPointerEXT},
    {"glOrtho", (void*)glOrtho},
    {"glPassTexCoordATI", (void*)glPassTexCoordATI},
    {"glPassThrough", (void*)glPassThrough},
    {"glPixelMapfv", (void*)glPixelMapfv},
    {"glPixelMapuiv", (void*)glPixelMapuiv},
    {"glPixelMapusv", (void*)glPixelMapusv},
    {"glPixelStoref", (void*)glPixelStoref},
    {"glPixelStorei", (void*)glPixelStorei},
    {"glPixelTransferf", (void*)glPixelTransferf},
    {"glPixelTransferi", (void*)glPixelTransferi},
    {"glPixelZoom", (void*)glPixelZoom},
    {"glPointParameterf", (void*)glPointParameterf},
    {"glPointParameterfARB", (void*)glPointParameterfARB},
    {"glPointParameterfEXT", (void*)glPointParameterfEXT},
    {"glPointParameterfv", (void*)glPointParameterfv},
    {"glPointParameterfvARB", (void*)glPointParameterfvARB},
    {"glPointParameterfvEXT", (void*)glPointParameterfvEXT},
    {"glPointParameteri", (void*)glPointParameteri},
    {"glPointParameteriNV", (void*)glPointParameteriNV},
    {"glPointParameteriv", (void*)glPointParameteriv},
    {"glPointParameterivNV", (void*)glPointParameterivNV},
    {"glPointSize", (void*)glPointSize},
    {"glPolygonMode", (void*)glPolygonMode},
    {"glPolygonOffset", (void*)glPolygonOffset},
    {"glPolygonOffsetEXT", (void*)glPolygonOffsetEXT},
    {"glPolygonStipple", (void*)glPolygonStipple},
    {"glPopAttrib", (void*)glPopAttrib},
    {"glPopClientAttrib", (void*)glPopClientAttrib},
    {"glPopMatrix", (void*)glPopMatrix},
    {"glPopName", (void*)glPopName},
    {"glPrioritizeTextures", (void*)glPrioritizeTextures},
    {"glPrioritizeTexturesEXT", (void*)glPrioritizeTexturesEXT},
    {"glProgramEnvParameter4dARB", (void*)glProgramEnvParameter4dARB},
    {"glProgramEnvParameter4dvARB", (void*)glProgramEnvParameter4dvARB},
    {"glProgramEnvParameter4fARB", (void*)glProgramEnvParameter4fARB},
    {"glProgramEnvParameter4fvARB", (void*)glProgramEnvParameter4fvARB},
    {"glProgramLocalParameter4dARB", (void*)glProgramLocalParameter4dARB},
    {"glProgramLocalParameter4dvARB", (void*)glProgramLocalParameter4dvARB},
    {"glProgramLocalParameter4fARB", (void*)glProgramLocalParameter4fARB},
    {"glProgramLocalParameter4fvARB", (void*)glProgramLocalParameter4fvARB},
    {"glProgramNamedParameter4dNV", (void*)glProgramNamedParameter4dNV},
    {"glProgramNamedParameter4dvNV", (void*)glProgramNamedParameter4dvNV},
    {"glProgramNamedParameter4fNV", (void*)glProgramNamedParameter4fNV},
    {"glProgramNamedParameter4fvNV", (void*)glProgramNamedParameter4fvNV},
    {"glProgramParameter4dNV", (void*)glProgramParameter4dNV},
    {"glProgramParameter4dvNV", (void*)glProgramParameter4dvNV},
    {"glProgramParameter4fNV", (void*)glProgramParameter4fNV},
    {"glProgramParameter4fvNV", (void*)glProgramParameter4fvNV},
    {"glProgramParameters4dvNV", (void*)glProgramParameters4dvNV},
    {"glProgramParameters4fvNV", (void*)glProgramParameters4fvNV},
    {"glProgramStringARB", (void*)glProgramStringARB},
    {"glPushAttrib", (void*)glPushAttrib},
    {"glPushClientAttrib", (void*)glPushClientAttrib},
    {"glPushMatrix", (void*)glPushMatrix},
    {"glPushName", (void*)glPushName},
    {"glRasterPos2d", (void*)glRasterPos2d},
    {"glRasterPos2dv", (void*)glRasterPos2dv},
    {"glRasterPos2f", (void*)glRasterPos2f},
    {"glRasterPos2fv", (void*)glRasterPos2fv},
    {"glRasterPos2i", (void*)glRasterPos2i},
    {"glRasterPos2iv", (void*)glRasterPos2iv},
    {"glRasterPos2s", (void*)glRasterPos2s},
    {"glRasterPos2sv", (void*)glRasterPos2sv},
    {"glRasterPos3d", (void*)glRasterPos3d},
    {"glRasterPos3dv", (void*)glRasterPos3dv},
    {"glRasterPos3f", (void*)glRasterPos3f},
    {"glRasterPos3fv", (void*)glRasterPos3fv},
    {"glRasterPos3i", (void*)glRasterPos3i},
    {"glRasterPos3iv", (void*)glRasterPos3iv},
    {"glRasterPos3s", (void*)glRasterPos3s},
    {"glRasterPos3sv", (void*)glRasterPos3sv},
    {"glRasterPos4d", (void*)glRasterPos4d},
    {"glRasterPos4dv", (void*)glRasterPos4dv},
    {"glRasterPos4f", (void*)glRasterPos4f},
    {"glRasterPos4fv", (void*)glRasterPos4fv},
    {"glRasterPos4i", (void*)glRasterPos4i},
    {"glRasterPos4iv", (void*)glRasterPos4iv},
    {"glRasterPos4s", (void*)glRasterPos4s},
    {"glRasterPos4sv", (void*)glRasterPos4sv},
    {"glReadBuffer", (void*)glReadBuffer},
    {"glReadPixels", (void*)glReadPixels},
    {"glRectd", (void*)glRectd},
    {"glRectdv", (void*)glRectdv},
    {"glRectf", (void*)glRectf},
    {"glRectfv", (void*)glRectfv},
    {"glRecti", (void*)glRecti},
    {"glRectiv", (void*)glRectiv},
    {"glRects", (void*)glRects},
    {"glRectsv", (void*)glRectsv},
    {"glRenderMode", (void*)glRenderMode},
    {"glRenderbufferStorageEXT", (void*)glRenderbufferStorageEXT},
    {"glRequestResidentProgramsNV", (void*)glRequestResidentProgramsNV},
    {"glResetHistogram", (void*)glResetHistogram},
    {"glResetMinmax", (void*)glResetMinmax},
    {"glResizeBuffersMESA", (void*)glResizeBuffersMESA},
    {"glRotated", (void*)glRotated},
    {"glRotatef", (void*)glRotatef},
    {"glSampleCoverage", (void*)glSampleCoverage},
    {"glSampleCoverageARB", (void*)glSampleCoverageARB},
    {"glSampleMapATI", (void*)glSampleMapATI},
    {"glScaled", (void*)glScaled},
    {"glScalef", (void*)glScalef},
    {"glScissor", (void*)glScissor},
    {"glSecondaryColor3b", (void*)glSecondaryColor3b},
    {"glSecondaryColor3bEXT", (void*)glSecondaryColor3bEXT},
    {"glSecondaryColor3bv", (void*)glSecondaryColor3bv},
    {"glSecondaryColor3bvEXT", (void*)glSecondaryColor3bvEXT},
    {"glSecondaryColor3d", (void*)glSecondaryColor3d},
    {"glSecondaryColor3dEXT", (void*)glSecondaryColor3dEXT},
    {"glSecondaryColor3dv", (void*)glSecondaryColor3dv},
    {"glSecondaryColor3dvEXT", (void*)glSecondaryColor3dvEXT},
    {"glSecondaryColor3f", (void*)glSecondaryColor3f},
    {"glSecondaryColor3fEXT", (void*)glSecondaryColor3fEXT},
    {"glSecondaryColor3fv", (void*)glSecondaryColor3fv},
    {"glSecondaryColor3fvEXT", (void*)glSecondaryColor3fvEXT},
    {"glSecondaryColor3i", (void*)glSecondaryColor3i},
    {"glSecondaryColor3iEXT", (void*)glSecondaryColor3iEXT},
    {"glSecondaryColor3iv", (void*)glSecondaryColor3iv},
    {"glSecondaryColor3ivEXT", (void*)glSecondaryColor3ivEXT},
    {"glSecondaryColor3s", (void*)glSecondaryColor3s},
    {"glSecondaryColor3sEXT", (void*)glSecondaryColor3sEXT},
    {"glSecondaryColor3sv", (void*)glSecondaryColor3sv},
    {"glSecondaryColor3svEXT", (void*)glSecondaryColor3svEXT},
    {"glSecondaryColor3ub", (void*)glSecondaryColor3ub},
    {"glSecondaryColor3ubEXT", (void*)glSecondaryColor3ubEXT},
    {"glSecondaryColor3ubv", (void*)glSecondaryColor3ubv},
    {"glSecondaryColor3ubvEXT", (void*)glSecondaryColor3ubvEXT},
    {"glSecondaryColor3ui", (void*)glSecondaryColor3ui},
    {"glSecondaryColor3uiEXT", (void*)glSecondaryColor3uiEXT},
    {"glSecondaryColor3uiv", (void*)glSecondaryColor3uiv},
    {"glSecondaryColor3uivEXT", (void*)glSecondaryColor3uivEXT},
    {"glSecondaryColor3us", (void*)glSecondaryColor3us},
    {"glSecondaryColor3usEXT", (void*)glSecondaryColor3usEXT},
    {"glSecondaryColor3usv", (void*)glSecondaryColor3usv},
    {"glSecondaryColor3usvEXT", (void*)glSecondaryColor3usvEXT},
    {"glSecondaryColorPointer", (void*)glSecondaryColorPointer},
    {"glSecondaryColorPointerEXT", (void*)glSecondaryColorPointerEXT},
    {"glSelectBuffer", (void*)glSelectBuffer},
    {"glSeparableFilter2D", (void*)glSeparableFilter2D},
    {"glSetFragmentShaderConstantATI", (void*)glSetFragmentShaderConstantATI},
    {"glShadeModel", (void*)glShadeModel},
    {"glShaderSource", (void*)glShaderSource},
    {"glShaderSourceARB", (void*)glShaderSourceARB},
    {"glStencilFunc", (void*)glStencilFunc},
    {"glStencilFuncSeparate", (void*)glStencilFuncSeparate},
    {"glStencilMask", (void*)glStencilMask},
    {"glStencilMaskSeparate", (void*)glStencilMaskSeparate},
    {"glStencilOp", (void*)glStencilOp},
    {"glStencilOpSeparate", (void*)glStencilOpSeparate},
    {"glTexCoord1d", (void*)glTexCoord1d},
    {"glTexCoord1dv", (void*)glTexCoord1dv},
    {"glTexCoord1f", (void*)glTexCoord1f},
    {"glTexCoord1fv", (void*)glTexCoord1fv},
    {"glTexCoord1i", (void*)glTexCoord1i},
    {"glTexCoord1iv", (void*)glTexCoord1iv},
    {"glTexCoord1s", (void*)glTexCoord1s},
    {"glTexCoord1sv", (void*)glTexCoord1sv},
    {"glTexCoord2d", (void*)glTexCoord2d},
    {"glTexCoord2dv", (void*)glTexCoord2dv},
    {"glTexCoord2f", (void*)glTexCoord2f},
    {"glTexCoord2fv", (void*)glTexCoord2fv},
    {"glTexCoord2i", (void*)glTexCoord2i},
    {"glTexCoord2iv", (void*)glTexCoord2iv},
    {"glTexCoord2s", (void*)glTexCoord2s},
    {"glTexCoord2sv", (void*)glTexCoord2sv},
    {"glTexCoord3d", (void*)glTexCoord3d},
    {"glTexCoord3dv", (void*)glTexCoord3dv},
    {"glTexCoord3f", (void*)glTexCoord3f},
    {"glTexCoord3fv", (void*)glTexCoord3fv},
    {"glTexCoord3i", (void*)glTexCoord3i},
    {"glTexCoord3iv", (void*)glTexCoord3iv},
    {"glTexCoord3s", (void*)glTexCoord3s},
    {"glTexCoord3sv", (void*)glTexCoord3sv},
    {"glTexCoord4d", (void*)glTexCoord4d},
    {"glTexCoord4dv", (void*)glTexCoord4dv},
    {"glTexCoord4f", (void*)glTexCoord4f},
    {"glTexCoord4fv", (void*)glTexCoord4fv},
    {"glTexCoord4i", (void*)glTexCoord4i},
    {"glTexCoord4iv", (void*)glTexCoord4iv},
    {"glTexCoord4s", (void*)glTexCoord4s},
    {"glTexCoord4sv", (void*)glTexCoord4sv},
    {"glTexCoordPointer", (void*)glTexCoordPointer},
    {"glTexCoordPointerEXT", (void*)glTexCoordPointerEXT},
    {"glTexEnvf", (void*)glTexEnvf},
    {"glTexEnvfv", (void*)glTexEnvfv},
    {"glTexEnvi", (void*)glTexEnvi},
    {"glTexEnviv", (void*)glTexEnviv},
    {"glTexGend", (void*)glTexGend},
    {"glTexGendv", (void*)glTexGendv},
    {"glTexGenf", (void*)glTexGenf},
    {"glTexGenfv", (void*)glTexGenfv},
    {"glTexGeni", (void*)glTexGeni},
    {"glTexGeniv", (void*)glTexGeniv},
    {"glTexImage1D", (void*)glTexImage1D},
    {"glTexImage2D", (void*)glTexImage2D},
    {"glTexImage3D", (void*)glTexImage3D},
    {"glTexImage3DEXT", (void*)glTexImage3DEXT},
    {"glTexParameterf", (void*)glTexParameterf},
    {"glTexParameterfv", (void*)glTexParameterfv},
    {"glTexParameteri", (void*)glTexParameteri},
    {"glTexParameteriv", (void*)glTexParameteriv},
    {"glTexSubImage1D", (void*)glTexSubImage1D},
    {"glTexSubImage1DEXT", (void*)glTexSubImage1DEXT},
    {"glTexSubImage2D", (void*)glTexSubImage2D},
    {"glTexSubImage2DEXT", (void*)glTexSubImage2DEXT},
    {"glTexSubImage3D", (void*)glTexSubImage3D},
    {"glTexSubImage3DEXT", (void*)glTexSubImage3DEXT},
    {"glTrackMatrixNV", (void*)glTrackMatrixNV},
    {"glTranslated", (void*)glTranslated},
    {"glTranslatef", (void*)glTranslatef},
    {"glUniform1f", (void*)glUniform1f},
    {"glUniform1fARB", (void*)glUniform1fARB},
    {"glUniform1fv", (void*)glUniform1fv},
    {"glUniform1fvARB", (void*)glUniform1fvARB},
    {"glUniform1i", (void*)glUniform1i},
    {"glUniform1iARB", (void*)glUniform1iARB},
    {"glUniform1iv", (void*)glUniform1iv},
    {"glUniform1ivARB", (void*)glUniform1ivARB},
    {"glUniform2f", (void*)glUniform2f},
    {"glUniform2fARB", (void*)glUniform2fARB},
    {"glUniform2fv", (void*)glUniform2fv},
    {"glUniform2fvARB", (void*)glUniform2fvARB},
    {"glUniform2i", (void*)glUniform2i},
    {"glUniform2iARB", (void*)glUniform2iARB},
    {"glUniform2iv", (void*)glUniform2iv},
    {"glUniform2ivARB", (void*)glUniform2ivARB},
    {"glUniform3f", (void*)glUniform3f},
    {"glUniform3fARB", (void*)glUniform3fARB},
    {"glUniform3fv", (void*)glUniform3fv},
    {"glUniform3fvARB", (void*)glUniform3fvARB},
    {"glUniform3i", (void*)glUniform3i},
    {"glUniform3iARB", (void*)glUniform3iARB},
    {"glUniform3iv", (void*)glUniform3iv},
    {"glUniform3ivARB", (void*)glUniform3ivARB},
    {"glUniform4f", (void*)glUniform4f},
    {"glUniform4fARB", (void*)glUniform4fARB},
    {"glUniform4fv", (void*)glUniform4fv},
    {"glUniform4fvARB", (void*)glUniform4fvARB},
    {"glUniform4i", (void*)glUniform4i},
    {"glUniform4iARB", (void*)glUniform4iARB},
    {"glUniform4iv", (void*)glUniform4iv},
    {"glUniform4ivARB", (void*)glUniform4ivARB},
    {"glUniformMatrix2fv", (void*)glUniformMatrix2fv},
    {"glUniformMatrix2fvARB", (void*)glUniformMatrix2fvARB},
    {"glUniformMatrix2x3fv", (void*)glUniformMatrix2x3fv},
    {"glUniformMatrix2x4fv", (void*)glUniformMatrix2x4fv},
    {"glUniformMatrix3fv", (void*)glUniformMatrix3fv},
    {"glUniformMatrix3fvARB", (void*)glUniformMatrix3fvARB},
    {"glUniformMatrix3x2fv", (void*)glUniformMatrix3x2fv},
    {"glUniformMatrix3x4fv", (void*)glUniformMatrix3x4fv},
    {"glUniformMatrix4fv", (void*)glUniformMatrix4fv},
    {"glUniformMatrix4fvARB", (void*)glUniformMatrix4fvARB},
    {"glUniformMatrix4x2fv", (void*)glUniformMatrix4x2fv},
    {"glUniformMatrix4x3fv", (void*)glUniformMatrix4x3fv},
    {"glUnlockArraysEXT", (void*)glUnlockArraysEXT},
    {"glUnmapBuffer", (void*)glUnmapBuffer},
    {"glUnmapBufferARB", (void*)glUnmapBufferARB},
    {"glUseProgram", (void*)glUseProgram},
    {"glUseProgramObjectARB", (void*)glUseProgramObjectARB},
    {"glValidateProgram", (void*)glValidateProgram},
    {"glValidateProgramARB", (void*)glValidateProgramARB},
    {"glVertex2d", (void*)glVertex2d},
    {"glVertex2dv", (void*)glVertex2dv},
    {"glVertex2f", (void*)glVertex2f},
    {"glVertex2fv", (void*)glVertex2fv},
    {"glVertex2i", (void*)glVertex2i},
    {"glVertex2iv", (void*)glVertex2iv},
    {"glVertex2s", (void*)glVertex2s},
    {"glVertex2sv", (void*)glVertex2sv},
    {"glVertex3d", (void*)glVertex3d},
    {"glVertex3dv", (void*)glVertex3dv},
    {"glVertex3f", (void*)glVertex3f},
    {"glVertex3fv", (void*)glVertex3fv},
    {"glVertex3i", (void*)glVertex3i},
    {"glVertex3iv", (void*)glVertex3iv},
    {"glVertex3s", (void*)glVertex3s},
    {"glVertex3sv", (void*)glVertex3sv},
    {"glVertex4d", (void*)glVertex4d},
    {"glVertex4dv", (void*)glVertex4dv},
    {"glVertex4f", (void*)glVertex4f},
    {"glVertex4fv", (void*)glVertex4fv},
    {"glVertex4i", (void*)glVertex4i},
    {"glVertex4iv", (void*)glVertex4iv},
    {"glVertex4s", (void*)glVertex4s},
    {"glVertex4sv", (void*)glVertex4sv},
    {"glVertexArrayRangeNV", (void*)glVertexArrayRangeNV},
    {"glVertexAttrib1d", (void*)glVertexAttrib1d},
    {"glVertexAttrib1dARB", (void*)glVertexAttrib1dARB},
    {"glVertexAttrib1dNV", (void*)glVertexAttrib1dNV},
    {"glVertexAttrib1dv", (void*)glVertexAttrib1dv},
    {"glVertexAttrib1dvARB", (void*)glVertexAttrib1dvARB},
    {"glVertexAttrib1dvNV", (void*)glVertexAttrib1dvNV},
    {"glVertexAttrib1f", (void*)glVertexAttrib1f},
    {"glVertexAttrib1fARB", (void*)glVertexAttrib1fARB},
    {"glVertexAttrib1fNV", (void*)glVertexAttrib1fNV},
    {"glVertexAttrib1fv", (void*)glVertexAttrib1fv},
    {"glVertexAttrib1fvARB", (void*)glVertexAttrib1fvARB},
    {"glVertexAttrib1fvNV", (void*)glVertexAttrib1fvNV},
    {"glVertexAttrib1s", (void*)glVertexAttrib1s},
    {"glVertexAttrib1sARB", (void*)glVertexAttrib1sARB},
    {"glVertexAttrib1sNV", (void*)glVertexAttrib1sNV},
    {"glVertexAttrib1sv", (void*)glVertexAttrib1sv},
    {"glVertexAttrib1svARB", (void*)glVertexAttrib1svARB},
    {"glVertexAttrib1svNV", (void*)glVertexAttrib1svNV},
    {"glVertexAttrib2d", (void*)glVertexAttrib2d},
    {"glVertexAttrib2dARB", (void*)glVertexAttrib2dARB},
    {"glVertexAttrib2dNV", (void*)glVertexAttrib2dNV},
    {"glVertexAttrib2dv", (void*)glVertexAttrib2dv},
    {"glVertexAttrib2dvARB", (void*)glVertexAttrib2dvARB},
    {"glVertexAttrib2dvNV", (void*)glVertexAttrib2dvNV},
    {"glVertexAttrib2f", (void*)glVertexAttrib2f},
    {"glVertexAttrib2fARB", (void*)glVertexAttrib2fARB},
    {"glVertexAttrib2fNV", (void*)glVertexAttrib2fNV},
    {"glVertexAttrib2fv", (void*)glVertexAttrib2fv},
    {"glVertexAttrib2fvARB", (void*)glVertexAttrib2fvARB},
    {"glVertexAttrib2fvNV", (void*)glVertexAttrib2fvNV},
    {"glVertexAttrib2s", (void*)glVertexAttrib2s},
    {"glVertexAttrib2sARB", (void*)glVertexAttrib2sARB},
    {"glVertexAttrib2sNV", (void*)glVertexAttrib2sNV},
    {"glVertexAttrib2sv", (void*)glVertexAttrib2sv},
    {"glVertexAttrib2svARB", (void*)glVertexAttrib2svARB},
    {"glVertexAttrib2svNV", (void*)glVertexAttrib2svNV},
    {"glVertexAttrib3d", (void*)glVertexAttrib3d},
    {"glVertexAttrib3dARB", (void*)glVertexAttrib3dARB},
    {"glVertexAttrib3dNV", (void*)glVertexAttrib3dNV},
    {"glVertexAttrib3dv", (void*)glVertexAttrib3dv},
    {"glVertexAttrib3dvARB", (void*)glVertexAttrib3dvARB},
    {"glVertexAttrib3dvNV", (void*)glVertexAttrib3dvNV},
    {"glVertexAttrib3f", (void*)glVertexAttrib3f},
    {"glVertexAttrib3fARB", (void*)glVertexAttrib3fARB},
    {"glVertexAttrib3fNV", (void*)glVertexAttrib3fNV},
    {"glVertexAttrib3fv", (void*)glVertexAttrib3fv},
    {"glVertexAttrib3fvARB", (void*)glVertexAttrib3fvARB},
    {"glVertexAttrib3fvNV", (void*)glVertexAttrib3fvNV},
    {"glVertexAttrib3s", (void*)glVertexAttrib3s},
    {"glVertexAttrib3sARB", (void*)glVertexAttrib3sARB},
    {"glVertexAttrib3sNV", (void*)glVertexAttrib3sNV},
    {"glVertexAttrib3sv", (void*)glVertexAttrib3sv},
    {"glVertexAttrib3svARB", (void*)glVertexAttrib3svARB},
    {"glVertexAttrib3svNV", (void*)glVertexAttrib3svNV},
    {"glVertexAttrib4Nbv", (void*)glVertexAttrib4Nbv},
    {"glVertexAttrib4NbvARB", (void*)glVertexAttrib4NbvARB},
    {"glVertexAttrib4Niv", (void*)glVertexAttrib4Niv},
    {"glVertexAttrib4NivARB", (void*)glVertexAttrib4NivARB},
    {"glVertexAttrib4Nsv", (void*)glVertexAttrib4Nsv},
    {"glVertexAttrib4NsvARB", (void*)glVertexAttrib4NsvARB},
    {"glVertexAttrib4Nub", (void*)glVertexAttrib4Nub},
    {"glVertexAttrib4NubARB", (void*)glVertexAttrib4NubARB},
    {"glVertexAttrib4Nubv", (void*)glVertexAttrib4Nubv},
    {"glVertexAttrib4NubvARB", (void*)glVertexAttrib4NubvARB},
    {"glVertexAttrib4Nuiv", (void*)glVertexAttrib4Nuiv},
    {"glVertexAttrib4NuivARB", (void*)glVertexAttrib4NuivARB},
    {"glVertexAttrib4Nusv", (void*)glVertexAttrib4Nusv},
    {"glVertexAttrib4NusvARB", (void*)glVertexAttrib4NusvARB},
    {"glVertexAttrib4bv", (void*)glVertexAttrib4bv},
    {"glVertexAttrib4bvARB", (void*)glVertexAttrib4bvARB},
    {"glVertexAttrib4d", (void*)glVertexAttrib4d},
    {"glVertexAttrib4dARB", (void*)glVertexAttrib4dARB},
    {"glVertexAttrib4dNV", (void*)glVertexAttrib4dNV},
    {"glVertexAttrib4dv", (void*)glVertexAttrib4dv},
    {"glVertexAttrib4dvARB", (void*)glVertexAttrib4dvARB},
    {"glVertexAttrib4dvNV", (void*)glVertexAttrib4dvNV},
    {"glVertexAttrib4f", (void*)glVertexAttrib4f},
    {"glVertexAttrib4fARB", (void*)glVertexAttrib4fARB},
    {"glVertexAttrib4fNV", (void*)glVertexAttrib4fNV},
    {"glVertexAttrib4fv", (void*)glVertexAttrib4fv},
    {"glVertexAttrib4fvARB", (void*)glVertexAttrib4fvARB},
    {"glVertexAttrib4fvNV", (void*)glVertexAttrib4fvNV},
    {"glVertexAttrib4iv", (void*)glVertexAttrib4iv},
    {"glVertexAttrib4ivARB", (void*)glVertexAttrib4ivARB},
    {"glVertexAttrib4s", (void*)glVertexAttrib4s},
    {"glVertexAttrib4sARB", (void*)glVertexAttrib4sARB},
    {"glVertexAttrib4sNV", (void*)glVertexAttrib4sNV},
    {"glVertexAttrib4sv", (void*)glVertexAttrib4sv},
    {"glVertexAttrib4svARB", (void*)glVertexAttrib4svARB},
    {"glVertexAttrib4svNV", (void*)glVertexAttrib4svNV},
    {"glVertexAttrib4ubNV", (void*)glVertexAttrib4ubNV},
    {"glVertexAttrib4ubv", (void*)glVertexAttrib4ubv},
    {"glVertexAttrib4ubvARB", (void*)glVertexAttrib4ubvARB},
    {"glVertexAttrib4ubvNV", (void*)glVertexAttrib4ubvNV},
    {"glVertexAttrib4uiv", (void*)glVertexAttrib4uiv},
    {"glVertexAttrib4uivARB", (void*)glVertexAttrib4uivARB},
    {"glVertexAttrib4usv", (void*)glVertexAttrib4usv},
    {"glVertexAttrib4usvARB", (void*)glVertexAttrib4usvARB},
    {"glVertexAttribPointer", (void*)glVertexAttribPointer},
    {"glVertexAttribPointerARB", (void*)glVertexAttribPointerARB},
    {"glVertexAttribPointerNV", (void*)glVertexAttribPointerNV},
    {"glVertexAttribs1dvNV", (void*)glVertexAttribs1dvNV},
    {"glVertexAttribs1fvNV", (void*)glVertexAttribs1fvNV},
    {"glVertexAttribs1svNV", (void*)glVertexAttribs1svNV},
    {"glVertexAttribs2dvNV", (void*)glVertexAttribs2dvNV},
    {"glVertexAttribs2fvNV", (void*)glVertexAttribs2fvNV},
    {"glVertexAttribs2svNV", (void*)glVertexAttribs2svNV},
    {"glVertexAttribs3dvNV", (void*)glVertexAttribs3dvNV},
    {"glVertexAttribs3fvNV", (void*)glVertexAttribs3fvNV},
    {"glVertexAttribs3svNV", (void*)glVertexAttribs3svNV},
    {"glVertexAttribs4dvNV", (void*)glVertexAttribs4dvNV},
    {"glVertexAttribs4fvNV", (void*)glVertexAttribs4fvNV},
    {"glVertexAttribs4svNV", (void*)glVertexAttribs4svNV},
    {"glVertexAttribs4ubvNV", (void*)glVertexAttribs4ubvNV},
    {"glVertexPointer", (void*)glVertexPointer},
    {"glVertexPointerEXT", (void*)glVertexPointerEXT},
    {"glViewport", (void*)glViewport},
    {"glWindowPos2d", (void*)glWindowPos2d},
    {"glWindowPos2dARB", (void*)glWindowPos2dARB},
    {"glWindowPos2dMESA", (void*)glWindowPos2dMESA},
    {"glWindowPos2dv", (void*)glWindowPos2dv},
    {"glWindowPos2dvARB", (void*)glWindowPos2dvARB},
    {"glWindowPos2dvMESA", (void*)glWindowPos2dvMESA},
    {"glWindowPos2f", (void*)glWindowPos2f},
    {"glWindowPos2fARB", (void*)glWindowPos2fARB},
    {"glWindowPos2fMESA", (void*)glWindowPos2fMESA},
    {"glWindowPos2fv", (void*)glWindowPos2fv},
    {"glWindowPos2fvARB", (void*)glWindowPos2fvARB},
    {"glWindowPos2fvMESA", (void*)glWindowPos2fvMESA},
    {"glWindowPos2i", (void*)glWindowPos2i},
    {"glWindowPos2iARB", (void*)glWindowPos2iARB},
    {"glWindowPos2iMESA", (void*)glWindowPos2iMESA},
    {"glWindowPos2iv", (void*)glWindowPos2iv},
    {"glWindowPos2ivARB", (void*)glWindowPos2ivARB},
    {"glWindowPos2ivMESA", (void*)glWindowPos2ivMESA},
    {"glWindowPos2s", (void*)glWindowPos2s},
    {"glWindowPos2sARB", (void*)glWindowPos2sARB},
    {"glWindowPos2sMESA", (void*)glWindowPos2sMESA},
    {"glWindowPos2sv", (void*)glWindowPos2sv},
    {"glWindowPos2svARB", (void*)glWindowPos2svARB},
    {"glWindowPos2svMESA", (void*)glWindowPos2svMESA},
    {"glWindowPos3d", (void*)glWindowPos3d},
    {"glWindowPos3dARB", (void*)glWindowPos3dARB},
    {"glWindowPos3dMESA", (void*)glWindowPos3dMESA},
    {"glWindowPos3dv", (void*)glWindowPos3dv},
    {"glWindowPos3dvARB", (void*)glWindowPos3dvARB},
    {"glWindowPos3dvMESA", (void*)glWindowPos3dvMESA},
    {"glWindowPos3f", (void*)glWindowPos3f},
    {"glWindowPos3fARB", (void*)glWindowPos3fARB},
    {"glWindowPos3fMESA", (void*)glWindowPos3fMESA},
    {"glWindowPos3fv", (void*)glWindowPos3fv},
    {"glWindowPos3fvARB", (void*)glWindowPos3fvARB},
    {"glWindowPos3fvMESA", (void*)glWindowPos3fvMESA},
    {"glWindowPos3i", (void*)glWindowPos3i},
    {"glWindowPos3iARB", (void*)glWindowPos3iARB},
    {"glWindowPos3iMESA", (void*)glWindowPos3iMESA},
    {"glWindowPos3iv", (void*)glWindowPos3iv},
    {"glWindowPos3ivARB", (void*)glWindowPos3ivARB},
    {"glWindowPos3ivMESA", (void*)glWindowPos3ivMESA},
    {"glWindowPos3s", (void*)glWindowPos3s},
    {"glWindowPos3sARB", (void*)glWindowPos3sARB},
    {"glWindowPos3sMESA", (void*)glWindowPos3sMESA},
    {"glWindowPos3sv", (void*)glWindowPos3sv},
    {"glWindowPos3svARB", (void*)glWindowPos3svARB},
    {"glWindowPos3svMESA", (void*)glWindowPos3svMESA},
    {"glWindowPos4dMESA", (void*)glWindowPos4dMESA},
    {"glWindowPos4dvMESA", (void*)glWindowPos4dvMESA},
    {"glWindowPos4fMESA", (void*)glWindowPos4fMESA},
    {"glWindowPos4fvMESA", (void*)glWindowPos4fvMESA},
    {"glWindowPos4iMESA", (void*)glWindowPos4iMESA},
    {"glWindowPos4ivMESA", (void*)glWindowPos4ivMESA},
    {"glWindowPos4sMESA", (void*)glWindowPos4sMESA},
    {"glWindowPos4svMESA", (void*)glWindowPos4svMESA},
    {"OSMesaCreateContext", (void*)OSMesaCreateContext },
    {"OSMesaCreateContextExt", (void*)OSMesaCreateContextExt},
    {"OSMesaDestroyContext", (void*)OSMesaDestroyContext},
    {"OSMesaMakeCurrent", (void*)OSMesaMakeCurrent},
    {"OSMesaGetCurrentContext", (void*)OSMesaGetCurrentContext},
    {"OSMesaPixelStore", (void*)OSMesaPixelStore},
    {"OSMesaGetIntegerv", (void*)OSMesaGetIntegerv},
    {"OSMesaGetDepthBuffer", (void*)OSMesaGetDepthBuffer},
    {"OSMesaGetColorBuffer", (void*)OSMesaGetColorBuffer},
    {"OSMesaColorClamp", (void*)OSMesaColorClamp},
    {NULL, NULL}
};

static void* osmesa_context = NULL;

static int OSMesa_LoadLibrary(_THIS, const char *path)
{
    return 0;
}

static void OSMesa_UnloadLibrary(_THIS)
{
}

static void* OSMesa_GetProcAddress(_THIS, const char *proc)
{
    for (int i=0; osmesa_symtab[i].name; i++) {
        if (SDL_strcmp(osmesa_symtab[i].name, proc) == 0) {
            return osmesa_symtab[i].addr;
        }
    }
    return NULL;
}

static int OSMesa_MakeCurrent(_THIS, SDL_Window * window, SDL_GLContext context)
{
    int height;
    int width;
    void *fb;

    SDL_GetWindowSize(window, &width, &height);
    fb = SDL_malloc(width * height * sizeof(GLubyte) * 4);
    if (!fb) {
        return SDL_SetError("Failed to allocate frame buffer");
    }

    if (!OSMesaMakeCurrent(context, fb, GL_UNSIGNED_BYTE, width, height)) {
        SDL_free(fb);
        return SDL_SetError("Failed to make context current");
    }

    osmesa_context = context;

    return 0;
}

static SDL_GLContext OSMesa_CreateContext(_THIS, SDL_Window * window)
{
    void* ctx;

    ctx = OSMesaCreateContext(GL_RGBA, NULL);
    if (!ctx) {
        SDL_SetError("Failed to create context");
        return NULL;
    }

    if(OSMesa_MakeCurrent(_this, window, ctx)) {
        return NULL;
    }

    return (SDL_GLContext)ctx;
}

static int OSMesa_SetSwapInterval(_THIS, int interval)
{
    return 0;
}

static int OSMesa_GetSwapInterval(_THIS)
{
    return 0;
}

static int OSMesa_SwapWindow(_THIS, SDL_Window *window)
{
    SDL_Surface *surface;
    int width, height;
    void *buffer;
    int format;

    if (!OSMesaGetColorBuffer(osmesa_context, &width, &height, &format, &buffer)) {
        return SDL_SetError("Failed to retrieve color buffer");
    }

    surface = SDL_GetWindowSurface(window);
    if (!surface) {
        return SDL_SetError("Failed to get SDL window surface");
    }

    if(surface->w != width || surface->h != height) {
        return SDL_SetError("Surface size does not match buffer size");
    }

    // memcpy(surface->pixels, buffer, width * height * sizeof(GLubyte) * 4);

    // Image will be upside-down from SDL's perspective, flip manually using an RGBA
    // variation of the math from:
    // https://github.com/vallentin/GLCollection/blob/master/screenshot.cpp
    //
    // Apparently this is necessary, since OpenGL doesn't provide a built-in way
    // to handle this:
    // https://www.opengl.org/archives/resources/features/KilgardTechniques/oglpitfall/
    for (int y = 0; y < height / 2; ++y) {
        for (int x = 0; x < width; ++x) {
            int top = (x + y * width) * 4;
            int bottom = (x + (height - y - 1) * width) * 4;
            char rgba[4];
            SDL_memcpy(rgba, buffer + top, sizeof(rgba));
            SDL_memcpy(surface->pixels + top, buffer + bottom, sizeof(rgba));
            SDL_memcpy(surface->pixels + bottom, rgba, sizeof(rgba));
        }
    }

    if (SDL_UpdateWindowSurface(window) != 0) {
        return SDL_SetError("Failed to update window surface");
    }

    return 0;
}

static void OSMesa_DeleteContext(_THIS, SDL_GLContext context)
{
    if (context) {
        OSMesaDestroyContext(context);
    }
}

static void OSMesa_DefaultProfileConfig(_THIS, int *mask, int *major, int *minor)
{
    *mask = SDL_GL_CONTEXT_PROFILE_CORE;
    *major = 2;
    *minor = 1;
}


int PS5_OSMesa_InitDevice(SDL_VideoDevice* device)
{
    device->GL_LoadLibrary = OSMesa_LoadLibrary;
    device->GL_GetProcAddress = OSMesa_GetProcAddress;
    device->GL_UnloadLibrary = OSMesa_UnloadLibrary;
    device->GL_CreateContext = OSMesa_CreateContext;
    device->GL_MakeCurrent = OSMesa_MakeCurrent;
    device->GL_SetSwapInterval = OSMesa_SetSwapInterval;
    device->GL_GetSwapInterval = OSMesa_GetSwapInterval;
    device->GL_SwapWindow = OSMesa_SwapWindow;
    device->GL_DeleteContext = OSMesa_DeleteContext;
    device->GL_DefaultProfileConfig = OSMesa_DefaultProfileConfig;

    return 0;
}


#endif
